name = "QMPS"
uuid = "c4dd8f60-5e06-11e9-07f8-63d1cb63a4d1"
authors = ["Frank Ws. Wang <frank.wang.w.s@gmail.com>"]
version = "0.3.3"

[deps]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"

[Compat]
julia = "1.3 - 1.4"
Yao = "0.6.2"